name: Run tests

on: [push, pull_request]

jobs:
    test:
        services:
            mariadb:
                image: mariadb
                ports:
                    - 3306:3306
                env:
                    MARIADB_ROOT_PASSWORD: root
                options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Use php 7.4
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "7.4"

            - uses: actions/cache@v3
              id: cache-wp-cli
              with:
                  path: ~/.wp-cli/cache
                  key: ${{ runner.os }}-wp-cli

            - name: Run tests
              run: .github/run-tests
